import type { Asset, Brand, Category } from "@/features/assets/types";

export const mockCategories: Category[] = [
	{ id: 1, name: "Electronics" },
	{ id: 2, name: "PC Components" },
	{ id: 3, name: "Camera" },
	{ id: 4, name: "Furniture" },
	{ id: 5, name: "Peripherals" },
];

export const mockBrands: Brand[] = [
	{ id: 1, name: "Logitech" },
	{ id: 2, name: "Sony" },
	{ id: 3, name: "NVIDIA" },
	{ id: 4, name: "IKEA" },
	{ id: 5, name: "Apple" },
];

export const mockAssets: Asset[] = [
	{
		id: 1,
		name: "MX Master 3S",
		model: null,
		serial: null,
		purchaseDate: "2024-08-12",
		purchasePrice: 99,
		currency: "USD",
		store: null,
		productUrl: null,
		condition: "new",
		warrantyExpiry: null,
		notes: null,
		categoryId: 5,
		category: { id: 5, name: "Peripherals" },
		brandId: null,
		brand: null,
		createdAt: "2024-08-12T10:00:00.000Z",
		updatedAt: "2024-08-12T10:00:00.000Z",
	},
	{
		id: 2,
		name: "RTX 4070 Super",
		model: "FE",
		serial: "N407S-22981",
		purchaseDate: "2024-03-02",
		purchasePrice: 599,
		currency: "USD",
		store: "Best Buy",
		productUrl: "https://example.com/rtx4070",
		condition: "new",
		warrantyExpiry: "2027-03-02",
		notes: "Extended warranty via store",
		categoryId: 2,
		category: { id: 2, name: "PC Components" },
		brandId: 3,
		brand: { id: 3, name: "NVIDIA" },
		createdAt: "2024-03-02T10:00:00.000Z",
		updatedAt: "2024-03-05T14:20:00.000Z",
	},
	{
		id: 3,
		name: "Markus Chair",
		model: null,
		serial: null,
		purchaseDate: "2023-11-20",
		purchasePrice: 180,
		currency: "USD",
		store: "IKEA",
		productUrl: null,
		condition: "used",
		warrantyExpiry: null,
		notes: null,
		categoryId: 4,
		category: { id: 4, name: "Furniture" },
		brandId: 4,
		brand: { id: 4, name: "IKEA" },
		createdAt: "2023-11-20T10:00:00.000Z",
		updatedAt: "2023-11-20T10:00:00.000Z",
	},
];
